### PR TITLE
Added some settings options and a new menu item

### PR DESCRIPTION
**Pull request by yeppiidev**
Added the following:
- Always show tabs setting
- Default new tab page setting
- Close all tabs except the current one menu item (in File menu)

### CODE REVIEW

**Comment by yeppiidev** [comment]
@Xexxa it would be nice if serenityos.net had a new tab search page

**Comment by yeppiidev** [comment]
Added a status bar, an 'always show tabs' option which will make the TabView always show tabs even if there's only a single tab, and a close all but current tab option

**Comment by Xexxa** [comment]
Hi @yeppiidev. I obviously feel honored that you added links to serenityos.net and wiki.serenityos.net, I hope you noticed that serenityos.**org** is the official site.

I added at your request [https://ladybird.serenityos.net/new-tab.html](https://ladybird.serenityos.net/new-tab.html) but it would be better to use the file in the SerenityOS repo [https://github.com/SerenityOS/serenity/blob/master/Base/res/html/misc/new-tab.html](https://github.com/SerenityOS/serenity/blob/master/Base/res/html/misc/new-tab.html) or if that is not possible, host a copy in the Ladybird repo.

I don't think a help menu would be merged after Andreas earlier statement: ["But for now, please treat ladybird as a debugging tool for LibWeb. :)"](https://github.com/awesomekling/ladybird/pull/20#issuecomment-1184351571)

The same goes with the statusbar, it was removed in an [earlier PR](https://github.com/awesomekling/ladybird/pull/22)

I would assume the additional settings could be merged.

Personally I like statusbars and help menus so I downstream many rejected PRs to my [fork](https://github.com/Xexxa/coccinellidae) :^) Just giving some useful info if you want this PR to get merged ;-)

**Comment by yeppiidev** [comment]
Thanks for the tips! I will remove the help menu (I too thought it was useless) and the statusbar 👍🏼

**Comment by yeppiidev** [comment]
Oh, I have no idea how to load files from the filesystem so I'm leaving that one for someone else

**Comment by AtkinsSJ** [comment]
This has conflicts.

**Comment by elcuco** [comment]
IMHO - this is safe to close, as main drifted from this branch way too much

**Comment by ADKaster** [comment]
Right, this has tons of conflicts and is almost 3 months at this point. if you rebase it and rework it I'm sure we could revive the spirit of the changes, which seem overall like a good idea. thanks for your contributions!

**Comment by yeppiidev** [comment]
yeah, i kind of messed up this PR so it was better to close this anyway. will contribute to serenity when possible 🙂

**Pull request closed without merging**
