### PR TITLE
CMake: Some debugging improvements

### PR DESCRIPTION
**Pull request by networkException**
This pull request adds flags for ASAN, MSAN and UBSAN as well as configures gdb to follow forks, making debugging WebContent with `ninja debug` a bit nicer

### CODE REVIEW

**Comment by networkException** [comment]
Is there a way to make MSAN ignore Qt?

**Comment by ADKaster** [comment]
> Is there a way to make MSAN ignore Qt?

What kind of errors are you seeing from MSAN? (And are you sure it's not LeakSanitizer?)

**Comment by networkException** [comment]
MemorySanitizer: use-of-uninitialized-value (Well it says MSAN on the box)

**Comment by ADKaster** [comment]
Ah, that sounds like the sort of thing valgrind would catch too. If it's reported by both then we should see if it's originating from a value we passed in. It's also possible there's suppressions in valgrind that we'd have to replicate.

**Comment by networkException** [comment]
Valgrind catches other things that don't look necessarily related but at least that doesn't cause the process to crash

**Pull request merged**
