### PR TITLE
Open link in new tab on mouse middle click

### PR DESCRIPTION
**Pull request by faxe1008**
This patch adds the functionality of opening the url pointed to by an anchor element when middle clicking it :^).

### CODE REVIEW

**Comment by AtkinsSJ** [comment]
Hi, this has some conflicts.

**Comment by faxe1008** [comment]
Rebased onto master, should build fine now :^)

**Comment by elcuco** [comment]
IMHO safe to close, as main drifted too much from this branch

**Comment by faxe1008** [comment]
> IMHO safe to close, as main drifted too much from this branch

yup, there was not enough interest in moving the PR further so I stopped rebasing :^)

**Pull request closed without merging**
